githubConfigUrl: "https://github.com/Bafff/idealista-tracker"

githubConfigSecret: arc-runner-secret

runnerScaleSetName: "idealista-5950x"

minRunners: 0
maxRunners: 5

containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 16000m
            memory: 20Gi
