apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner-idealista-deployer-sa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Bafff/github-runners.git
    targetRevision: HEAD
    path: manifests/idealista-deployer
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
